export const mockUserStaff = {
    id: 2,
    institution_id: 1,
    username: 'teacher',
    password: 'abcd123',
    first_name: 'Peter',
    other_name: 'Aikude',
    email: 'aaa@gg.com',
    phone: '+2341231234',
    active: true,
    admin: false,
    reset_code: '',
    avatar: '',
    personal_info: '',
    registration_source: '',
    enable_contact_me: true,
    role: 'FACULTY',
    student: {
        id: 1,
        reg_no: 1,
        user_id: 2,
        programme_id: 6,
        first_name: '',
        last_name: '',
        other_name: '',
        email: '',
        phone: '',
        address: '',
        gender: '',
        ref_fname: '',
        ref_lname: '',
        ref_phone: '',
        ref_address: ''
    }
}

export const mockUserStudent = {
    id: 3,
    institution_id: 1,
    username: '',
    password: '',
    first_name: '',
    other_name: '',
    email: '',
    phone: '',
    active: true,
    admin: false,
    reset_code: '',
    avatar: '',
    personal_info: '',
    registration_source: '',
    enable_contact_me: true,
    role: 'STUDENT',
    student: {
        id: 1,
        reg_no: 1,
        user_id: 3,
        programme_id: 6,
        firts_name: '',
        last_name: '',
        other_name: '',
        email: '',
        phone: '',
        address: '',
        gender: '',
        ref_fname: '',
        ref_lname: '',
        ref_phone: '',
        ref_address: ''
    }
}