"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, Sparkles } from "lucide-react";
import PracticeQuestionGenerator from "@/components/practice-test/PracticeQuestionGenerator";
import ExistingPracticeQuestions from "@/components/practice-test/ExistingPracticeQuestions";

interface PracticeTestSectionProps {
  courseLessonId?: number;
  lessonName?: string;
  showSection?: boolean;
}

export default function PracticeTestSection({
  courseLessonId,
  lessonName,
  showSection = true,
}: PracticeTestSectionProps) {
  // Don't render if showSection is false or no lessonId
  if (!showSection || !courseLessonId) {
    return null;
  }

  return (
    <Card className="mb-6 border border-border bg-card">
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <Brain className="h-5 w-5 text-primary" />
          <span>AI Practice Questions</span>
          <div className="flex items-center space-x-1 ml-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <span className="text-sm text-primary font-normal">
              AI-Powered
            </span>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent>
        {/* Existing Practice Questions */}
        <ExistingPracticeQuestions
          lessonId={courseLessonId}
          lessonName={lessonName || "Current Lesson"}
        />

        {/* AI Practice Question Generator */}
        <div className="mt-4">
          <PracticeQuestionGenerator
            lessonId={courseLessonId}
            lessonName={lessonName || "Current Lesson"}
          />
        </div>

        {/* Info Section */}
        <div className="mt-4 p-3 bg-muted/30 rounded-lg border border-border/60">
          <p className="text-sm text-muted-foreground">
            <strong>✨ AI Practice Questions:</strong> Get personalized practice
            questions generated by AI based on your lesson content. Practice as
            many times as you want with instant explanations - no grades
            recorded, just pure learning!
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
