const getProfile = {
  tags: ["profile"],
  description:
    "Get complete profile data including user, student/staff, and institution information",
  params: {
    type: "object",
    properties: {
      id: {
        type: "integer",
        description: "User ID (optional - defaults to authenticated user)",
      },
    },
  },
  response: {
    200: {
      type: "object",
      properties: {
        user: {
          type: "object",
          properties: {
            id: { type: "integer" },
            username: { type: "string" },
            first_name: { type: "string" },
            last_name: { type: "string" },
            other_name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            role: { type: "string" },
            avatar: { type: "string" },
            institution_id: { type: "integer" },
            active: { type: "boolean" },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
        },
        student: {
          type: ["object", "null"],
          properties: {
            id: { type: "integer" },
            reg_no: { type: "string" },
            user_id: { type: "integer" },
            gender: { type: "string" },
            dob: { type: "string" },
            address: { type: "string" },
            marital_status: { type: "string" },
            employment_status: { type: "string" },
            state_origin: { type: "string" },
            lga_origin: { type: "string" },
            state_residence: { type: "string" },
            lga_residence: { type: "string" },
            programme_id: { type: "integer" },
            semester_admitted_id: { type: "integer" },
            entry_level_id: { type: "integer" },
            admission_status: { type: "string" },
            course_studied: { type: "string" },
            inst_name: { type: "string" },
            inst_type: { type: "string" },
            degree_grade: { type: "string" },
            type_degree: { type: "string" },
            grad_year: { type: "string" },
            created_at: { type: "string" },
            updated_at: { type: "string" },
            programme: {
              type: "object",
              properties: {
                id: { type: "integer" },
                name: { type: "string" },
                code: { type: "string" },
                department_id: { type: "integer" },
                faculty_id: { type: "integer" },
                duration: { type: "string" },
                years: { type: "integer" },
                prefix: { type: "string" },
                description: { type: "string" },
                regno_format: { type: "string" },
                created_at: { type: "string" },
                updated_at: { type: "string" },
                department: {
                  type: "object",
                  properties: {
                    id: { type: "integer" },
                    faculty_id: { type: "integer" },
                    code: { type: "string" },
                    name: { type: "string" },
                    email: { type: "string" },
                    phone: { type: "string" },
                    description: { type: "string" },
                    created_at: { type: "string" },
                    updated_at: { type: "string" },
                    faculty: {
                      type: "object",
                      properties: {
                        id: { type: "integer" },
                        institution_id: { type: "integer" },
                        name: { type: "string" },
                        code: { type: "string" },
                        email: { type: "string" },
                        phone: { type: "string" },
                        description: { type: "string" },
                        created_at: { type: "string" },
                        updated_at: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
            semester: {
              type: "object",
              properties: {
                id: { type: "integer" },
                name: { type: "string" },
                start_date: { type: "string" },
                end_date: { type: "string" },
                session_id: { type: "integer" },
              },
            },
            current_semester: {
              type: "object",
              properties: {
                id: { type: "integer" },
                name: { type: "string" },
                start_date: { type: "string" },
                end_date: { type: "string" },
                session_id: { type: "integer" },
                active: { type: "boolean" },
              },
            },
            registered_courses_count: { type: "integer" },
            approved_courses_count: { type: "integer" },
          },
        },
        staff: {
          type: ["object", "null"],
          description: "Staff information if user is staff",
        },
        institution: {
          type: ["object", "null"],
          properties: {
            id: { type: "integer" },
            name: { type: "string" },
            code: { type: "string" },
            address: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            website: { type: "string" },
            logo: { type: "string" },
            id_card: {
              type: "object",
              properties: {
                front: { type: "string" },
                back: { type: "string" },
              },
            },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
        },
      },
    },
  },
};

const updateProfile = {
  tags: ["profile"],
  description: "Update profile data (user info, student info, and password)",
  params: {
    type: "object",
    properties: {
      id: {
        type: "integer",
        description: "User ID (optional - defaults to authenticated user)",
      },
    },
  },
  body: {
    type: "object",
    properties: {
      user: {
        type: "object",
        properties: {
          first_name: { type: "string" },
          last_name: { type: "string" },
          other_name: { type: "string" },
          phone: { type: "string" },
          avatar: { type: "string" },
        },
      },
      student: {
        type: "object",
        properties: {
          address: { type: "string" },
          dob: { type: "string", format: "date" },
          gender: { type: "string", enum: ["MALE", "FEMALE", "OTHER"] },
          marital_status: {
            type: "string",
            enum: ["SINGLE", "MARRIED", "DIVORCED", "WIDOWED"],
          },
          employment_status: { type: "string" },
          state_origin: { type: "string" },
          lga_origin: { type: "string" },
          state_residence: { type: "string" },
          lga_residence: { type: "string" },
          course_studied: { type: "string" },
          inst_name: { type: "string" },
          inst_type: { type: "string" },
          degree_grade: { type: "string" },
          type_degree: { type: "string" },
          grad_year: { type: "string" },
        },
      },
      password: {
        type: "object",
        properties: {
          currentPassword: { type: "string" },
          newPassword: { type: "string" },
          confirmPassword: { type: "string" },
        },
        required: ["currentPassword", "newPassword", "confirmPassword"],
      },
    },
  },
  response: {
    200: {
      type: "object",
      properties: {
        user: {
          type: "object",
          properties: {
            id: { type: "integer" },
            username: { type: "string" },
            first_name: { type: "string" },
            last_name: { type: "string" },
            other_name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            role: { type: "string" },
            avatar: { type: "string" },
            institution_id: { type: "integer" },
            active: { type: "boolean" },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
        },
        student: {
          type: ["object", "null"],
          properties: {
            id: { type: "integer" },
            reg_no: { type: "string" },
            user_id: { type: "integer" },
            gender: { type: "string" },
            dob: { type: "string" },
            address: { type: "string" },
            marital_status: { type: "string" },
            employment_status: { type: "string" },
            state_origin: { type: "string" },
            lga_origin: { type: "string" },
            state_residence: { type: "string" },
            lga_residence: { type: "string" },
            programme_id: { type: "integer" },
            semester_admitted_id: { type: "integer" },
            entry_level_id: { type: "integer" },
            admission_status: { type: "string" },
            course_studied: { type: "string" },
            inst_name: { type: "string" },
            inst_type: { type: "string" },
            degree_grade: { type: "string" },
            type_degree: { type: "string" },
            grad_year: { type: "string" },
            created_at: { type: "string" },
            updated_at: { type: "string" },
            programme: {
              type: "object",
              properties: {
                id: { type: "integer" },
                name: { type: "string" },
                code: { type: "string" },
                department_id: { type: "integer" },
                faculty_id: { type: "integer" },
                duration: { type: "string" },
                years: { type: "integer" },
                prefix: { type: "string" },
                description: { type: "string" },
                regno_format: { type: "string" },
                created_at: { type: "string" },
                updated_at: { type: "string" },
                department: {
                  type: "object",
                  properties: {
                    id: { type: "integer" },
                    faculty_id: { type: "integer" },
                    code: { type: "string" },
                    name: { type: "string" },
                    email: { type: "string" },
                    phone: { type: "string" },
                    description: { type: "string" },
                    created_at: { type: "string" },
                    updated_at: { type: "string" },
                    faculty: {
                      type: "object",
                      properties: {
                        id: { type: "integer" },
                        institution_id: { type: "integer" },
                        name: { type: "string" },
                        code: { type: "string" },
                        email: { type: "string" },
                        phone: { type: "string" },
                        description: { type: "string" },
                        created_at: { type: "string" },
                        updated_at: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
            semester: {
              type: "object",
              properties: {
                id: { type: "integer" },
                name: { type: "string" },
                start_date: { type: "string" },
                end_date: { type: "string" },
                session_id: { type: "integer" },
              },
            },
            current_semester: {
              type: "object",
              properties: {
                id: { type: "integer" },
                name: { type: "string" },
                start_date: { type: "string" },
                end_date: { type: "string" },
                session_id: { type: "integer" },
                active: { type: "boolean" },
              },
            },
            registered_courses_count: { type: "integer" },
            approved_courses_count: { type: "integer" },
          },
        },
        staff: {
          type: ["object", "null"],
          description: "Staff information if applicable",
        },
        institution: {
          type: ["object", "null"],
          properties: {
            id: { type: "integer" },
            name: { type: "string" },
            code: { type: "string" },
            address: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            website: { type: "string" },
            logo: { type: "string" },
            created_at: { type: "string" },
            updated_at: { type: "string" },
          },
        },
        message: {
          type: "string",
          description: "Success message",
        },
      },
    },
  },
};

module.exports = {
  getProfile,
  updateProfile,
};
